### ISSUE TITLE
Include a lot of semantical information in addition to the (tree) structure

### ISSUE THREAD

**Issue by dumblob** [Aetf/tensorflow-tbcnn#2]
In the paper of yours you're mentioning a further work including extension with capturing semantical information ("what the input strings or integeres or ... contain or even mean", "what are the relationships between the contents of different strings", etc.).

Did you make any progress on this? I came across a tree-like problem which is though very sensitive to the contents of the leafs and I'm first looking for existing approaches to the problem before I start with something on my own.

**Comment by Aetf** [comment]
Sorry, I haven't been working on the project for a while.
