### ISSUE TITLE
SQl parser

### ISSUE THREAD

**Issue by Dskpupper** [Aetf/tensorflow-tbcnn#4]
Hey, I just  need the sql parser script that  you used to parser the sql payload and collect the dataset.
Just that part. which file is it?

**Comment by Aetf** [comment]
The initial data was parsed by [pg_query](https://wiki.postgresql.org/wiki/Query_Parsing#pg_query) and then the JSON results were manually edited and cleaned up for this project.

In this project the dataset is no longer raw SQL text, but python pickle dumps. You can find more details in `data.py`.
